// Generated by Quartus II Version 9.1 
// Created on Sat Dec 16 20:30:45 2023

lab_2 lab_2_inst
(
	.sw(sw_sig) ,	// input [3]:w[3]] sw_sig
	.sw(sw_sig) ,	// input [4]:w[4]] sw_sig
	.KEY(KEY_sig) ,	// input [2]:EY[2]] KEY_sig
	.KEY(KEY_sig) ,	// input [3]:EY[3]] KEY_sig
	.LEDR(LEDR_sig) 	// output [9]:EDR[9]] LEDR_sig
);