// Generated by Quartus II Version 9.1 
// Created on Sat Dec 16 20:26:46 2023

circuito_comb circuito_inst
(
	.SW(SW_sig) ,	// input [3]:W[3]] SW_sig
	.SW(SW_sig) ,	// input [2]:W[2]] SW_sig
	.SW(SW_sig) ,	// input [1]:W[1]] SW_sig
	.SW(SW_sig) ,	// input [0]:W[0]] SW_sig
	.HEX0(HEX0_sig) ,	// output [0]:EX0[0]] HEX0_sig
	.HEX0(HEX0_sig) ,	// output [1]:EX0[1]] HEX0_sig
	.HEX0(HEX0_sig) ,	// output [2]:EX0[2]] HEX0_sig
	.HEX0(HEX0_sig) ,	// output [3]:EX0[3]] HEX0_sig
	.HEX0(HEX0_sig) ,	// output [4]:EX0[4]] HEX0_sig
	.HEX0(HEX0_sig) ,	// output [6]:EX0[6]] HEX0_sig
	.HEX0(HEX0_sig) 	// output [5]:EX0[5]] HEX0_sig
);